### ISSUE TITLE
Making function reusable

### ISSUE THREAD

**Issue by doraithodla** [Lakshmipriya0404/text-extraction#1]
Make the  text_from_pdf() take the pdf name as a parameter to make the function more reusable.

**Comment by Lakshmipriya0404** [comment]
Yes sir, I updated. From: Dorai ThodlaSent: 12 April 2023 07:41To: Lakshmipriya0404/text-extractionCc: SubscribedSubject: [Lakshmipriya0404/text-extraction] Making function reusable (Issue #1) Make the text_from_pdf() take the pdf name as a parameter to make the function more reusable.—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you are subscribed to this thread.Message ID: ***@***.***>
